server:
  port: 8280

spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/hellchang #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

  jpa: #띄어쓰기 2칸
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
        show_sql: true #이향준 추가
    defer-datasource-initialization: true

  mvc:
    hidden-method:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enable: false #운영에서는 제거

  #네이버 smtp 설정
  mail:
    host: smtp.naver.com
    port: 465
    username: gidwns617
    password: 65BB4KPHR4QR
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com

logging:
  level: #띄어쓰기 없음
    org.hibernate.SQL: debug #띄어쓰기 2칸